### ISSUE TITLE
Adding color coding

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/Zonemaster-GUI--ARCHIVED-OLD-VERSION-NOT-TO-BE-USED#154]
1. Notice should be Yellow
2. Warning should be Orange
3. Error should be Red 
4. Info should be light blue

Change the color for the different policy level.

Also, when the user moves the cursor to different policy levels, he should have an idea what the policy states.

Notice -  means something that should be known by the zone's administrator but that need not necessarily be a problem at all.
Warning - means something that will under some circumstances be a problem, but that is unlikely to be noticed by a casual user
Info - is something that may be of interest to the zone's administrator but that definitely does not indicate a problem.
Error - means a problem that is very likely (or possibly certain) to negatively affect the function of the zone being tested, but not so severe that the entire zone becomes unresolvable

**Comment by sandoche2k** [comment]
@pamasse for the new GUI please follow the above color coding

**Comment by pamasse** [comment]
Done with the new GUI but need translation of notice, info, etc... explications.

**Comment by sandoche2k** [comment]
@pamasse "notice" is still green

**Comment by pamasse** [comment]
Fix for result too and not only the filter menu

**Comment by matsduf** [comment]
I just looked at https://zonemaster.afnic-labs.fr/domain_check and I would rather have green for info and a level with only info and notice.
