### ISSUE TITLE
Make sending client IP optional

### ISSUE THREAD

**Issue by matsduf** [zonemaster/Zonemaster-GUI--ARCHIVED-OLD-VERSION-NOT-TO-BE-USED#173]
The GUI send the client IP to the backend, which stores the information in the backend. Make that an optional feature, i.e. make it possible to configure the GUI so that the IP address is never sent to the backend.

If sending IP address is enabled, it could be considered to make it possible to let the user select if its IP address should be stored. Maybe that should be configurable for the GUI too.

**Comment by sandoche2k** [comment]
@pamasse is this issue taken care by the new GUI?

**Comment by pamasse** [comment]
Fixed with the new GUI

**Comment by sandoche2k** [comment]
@sandoche2k to verify during testing
