### ISSUE TITLE
Certain files are not in the GUI directory while installing from CPAN

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/Zonemaster-GUI--ARCHIVED-OLD-VERSION-NOT-TO-BE-USED#175]
e.g. zm_app 

was found here: 
/home/sandoche/.cpan/build/Zonemaster-GUI-1.0.7-SKLJy5/zm_app whereas it was expected here : 

:/usr/local/lib/x86_64-linux-gnu/perl/5.22.1/auto/Zonemaster/GUI

**Comment by matsduf** [comment]
That is a directory with various files, isn't it? They should be put in different directories, shouldn't they?

**Comment by pamasse** [comment]
Fixed with the new GUI

**Comment by sandoche2k** [comment]
@sandoche2k check during installation and testing process.
