### ISSUE TITLE
New GUI: Error in time and date display

### ISSUE THREAD

**Issue by matsduf** [zonemaster/Zonemaster-GUI--ARCHIVED-OLD-VERSION-NOT-TO-BE-USED#230]
Running a test, and the new GUI says: "Executed at 6/19/18, 10:14 AM GMT+2" or (for Swedish) "Körd 6/19/18, 10:14 AM GMT+2".

Error one is that the actual time is UTC, not UTC+2.

Error two is that the date format for Swedish is not -- Swedish.

**Comment by pamasse** [comment]
hi, something like this ?:  
FR:  19 juin 2018 14:04 
SV: Körd 19 juni 2018 kl. 14:04 
EN:  June 19, 2018 2:04 PM 
DA:  19. juni 2018 14:04

**Comment by matsduf** [comment]
"Körd" means "executed, so just "19 juni 2018 kl. 14:04". I think it make sense to tell what timezone it refers to.

**Comment by pamasse** [comment]
Ok, i will remove the "executed at:", and the time is in UTC.
It's fine ?

**Comment by matsduf** [comment]
It is fine, but...

Can the GUI pick the local timezone up from the computer running it? If so, I think it would be even nicer if it could display the time in the local timezone plus displaying it. But that is extra feature. :-)

**Comment by pamasse** [comment]
Well, we can do that but not for now (need more work).

**Comment by pamasse** [comment]
Well, i added this feature without displaying the UTC, it's quite hard to calculate it.
