### ISSUE TITLE
New GUI: some display behavior

### ISSUE THREAD

**Issue by matsduf** [zonemaster/Zonemaster-GUI--ARCHIVED-OLD-VERSION-NOT-TO-BE-USED#231]
Report from Niall:

I've noticed some questionable presentation behaviour from zonemaster.fr,
probably to do with the alpha status of the GUI (GUI-2.0.0-alpha), which
may already be represented on your snag list.

1.	For a test group whose display is collapsed, the tooltip shown
when the cursor is moved over the '+' shows the label 'Collapse'
instead of 'Expand'.

2.	Propagation of the appropriate background colour seems inconsistent;
group headings for which 'notice' messages have been generated may
be shown either with the expected yellow background or with a
blue background. A current example may be found by running a test
against no8.be, for which 'notice' messages are generated under four
headings, of which two ('ADDRESS', 'DNSSEC') are shown on a
yellow background, and another two ('NAMESERVER', 'ZONE') on
a blue one. In the expanded view, the 'notice' messages are shown
on the expected yellow background.

**Comment by pamasse** [comment]
Fixed, i will push soon + move the repo zonemaster/zonemaster-gui
