### ISSUE TITLE
History of previous tests should preload

### ISSUE THREAD

**Issue by pawal** [zonemaster/Zonemaster-GUI--ARCHIVED-OLD-VERSION-NOT-TO-BE-USED#47]
_From @einar on November 13, 2014 15:54_

As it is now you have to complete a test to get history for a domain (unless it has been cached). If possible we should preload the history as soon as a user confirms a test (with all the links to previous runs) so he doesnt have to wait a full test cycle if he simply wants to see history.

Yes, there's a use case for this. I do it all the time when people ask me about results; I start a test on the same domain then just jump to their actual test in the list instead of completing my own (since few people remember to send a link). ;)

_Copied from original issue: dotse/zonemaster#209_

**Comment by pawal** [comment]
Need input from @einar - how should it work in detail? Use an additional button for this?

**Comment by einar** [comment]
Nah, similar function as we had in DNSCheck would be fine I think. In DNSCheck the history-page loads as soon as the test is started (not waiting for it to complete as Zonemaster does).

Perhaps we could let the righthand page load with History as default as soon as a test starts and then (unless the user clicks a History-link) just go back to Basic and display the results?

**Comment by sandoche2k** [comment]
@pawal - pls. move it to release .4

**Comment by sandoche2k** [comment]
could be closed with the new GUI @pamasse

**Comment by pamasse** [comment]
Not sure to see the benefits but it's not yet implemented in the new GUI.
