### ISSUE TITLE
Create an API suitable for the public

### ISSUE THREAD

**Issue by pawal** [zonemaster/Zonemaster-GUI--ARCHIVED-OLD-VERSION-NOT-TO-BE-USED#54]
We have an internal API that the web gui uses, but we should consider to offer a public API suitable for automatic testing available to the public.

**Comment by sandoche2k** [comment]
@pawal move to priority low (Survey results)

**Comment by sandoche2k** [comment]
@pawal pls. move to Icebox

**Comment by pamasse** [comment]
Can be closed. It will be done in the Backend.
