### ISSUE TITLE
Internationalization of error messages

### ISSUE THREAD

**Issue by mtoma** [zonemaster/Zonemaster-GUI--ARCHIVED-OLD-VERSION-NOT-TO-BE-USED#84]
All JavaScript alerts are in English only.
ex: test afn_ic.fr in the user interface

**Comment by sandoche2k** [comment]
@pawal assign to @mtoma and for release .4

**Comment by sandoche2k** [comment]
@pamasse the new GUI should include this feature

**Comment by pamasse** [comment]
Done :)
But only in french and english. For SV and DA, it must be done in translate files.
in /src/assets/i18n/da.json and /src/assets/i18n/sv.json
